pre-commit hook tweaks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -48,6 +48,20 @@
 # # If there are whitespace errors, print the offending file names and fail.
 # exec git diff-index --check --cached $against --
 
+yarn audit --groups=dependencies --level=critical
+
+if [ $? == 1 ]
+  then
+    exit 1
+elif [ $? \< 16 ]
+  then
+    exit 0
+  else
+    echo "\033[33mCommit failed, critical security vulnerability found in one of the project's dependencies. Please resolve as per the audit report above, then re-commit.\033[0m"
+    exit 1
+fi
+
 yarn test-cov
 yarn lint
-yarn audit; [[ $? -ge 16 ]] && exit $? || exit 0
+
+
