pre-commit hook tweaks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -52,10 +52,13 @@ yarn test-cov
 yarn lint
 yarn audit --groups=dependencies --level=critical
 
-if [ $? \< 16 ]
+if [ $? == 1 ]
+  then
+    exit 1
+elif [ $? \< 16 ]
   then
     exit 0
   else
-    echo "\e[31mCommit failed, critical security vulnerability found in one of the project's dependencies. Please resolve as per the audit report above, then re-commit.\e[0m"
+    echo "\033[33mCommit failed, critical security vulnerability found in one of the project's dependencies. Please resolve as per the audit report above, then re-commit.\033[0m"
     exit 1
 fi
