Test with urls

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -87,14 +87,16 @@ jobs:
           username: _json_key # default username when using a JSON key file to authenticate
           password: $GCLOUD_SERVICE_KEY
     steps:
-      # - "setup_remote_docker"
-      # - "docker_login"
   #     #TODO rename the site so tests can be executed in each specific site
       - run: |
           cd /app
+          export SITE_DOMAIN=$(echo "${CIRCLE_BRANCH}" | tr '[:upper:]' '[:lower:]')
+          export URL="https://${SITE_DOMAIN}.pamdas.org/login"
+          export URL_ADMIN="https://${SITE_DOMAIN}.pamdas.org/admin/login"
           env > .env
-          npm run test:cloud || { echo 'Tests failed'; exit 1; }
-          npm run reporter:cloud || { echo 'Report failed'; exit 1; }
+          cat .env
+      #    npm run test:cloud || { echo 'Tests failed'; exit 1; }
+      #    npm run reporter:cloud || { echo 'Report failed'; exit 1; }
       #     echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
       #     gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
       #     gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
