Update config yaml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -48,16 +48,11 @@ jobs:
       - run: "ci-helpers/makeversion.py"
       - node/install-packages:
           cache-path: ~/project/node_modules
-          override-ci-command: npm install --ignore-scripts
+          override-ci-command: npm install
       - run: 
           command: npm run test-ci
           environment:
             NODE_OPTIONS: --max_old_space_size=8192 
-      - run:
-          command: npm rebuild node-sass
-          name: Rebuild node-sass
-          environment:
-            NODE_OPTIONS: --max_old_space_size=8192
       - run:
           command: CI=false npm run build
           name: Build Production Artefact
@@ -92,21 +87,23 @@ jobs:
           username: _json_key # default username when using a JSON key file to authenticate
           password: $GCLOUD_SERVICE_KEY
     steps:
+  #     #TODO rename the site so tests can be executed in each specific site
       - run: |
           cd /app
           export SITE_DOMAIN=$(echo "${CIRCLE_BRANCH}" | tr '[:upper:]' '[:lower:]')
           export URL="https://${SITE_DOMAIN}.pamdas.org/login"
           export URL_ADMIN="https://${SITE_DOMAIN}.pamdas.org/admin/login"
           env > .env
-          TEST_RESULT=0
-          npm run test:cloud || { TEST_RESULT=1 }
+          TEST_RESULT-
+          npm run test:cloud || { TEST_RESULT=1; }
           npm run reporter:cloud
           echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
           gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
           gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
-          gsutil cp -r ./results/allure-raw gs://er-report-test/
+          gsutil cp -r ./_results_/allure-raw gs://er-report-test/
           gsutil cp -r ./allure-report gs://er-report-test/
-        #  if [[ ${TEST_RESULT} == 1 ]]; then echo "Tests failed" && exit 1; fi
+          if [[ ${TEST_RESULT} == 1 ]]; then echo "Tests failed" && exit 1; fi
+
 
 workflows:
   version: 2
