Update circleci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -92,7 +92,6 @@ jobs:
           username: _json_key # default username when using a JSON key file to authenticate
           password: $GCLOUD_SERVICE_KEY
     steps:
-  #     #TODO rename the site so tests can be executed in each specific site
       - run: |
           cd /app
           export SITE_DOMAIN=$(echo "${CIRCLE_BRANCH}" | tr '[:upper:]' '[:lower:]')
@@ -105,9 +104,9 @@ jobs:
           echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
           gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
           gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
-          gsutil cp -r ./allure-raw gs://er-report-test/
-          if [[ ${TEST_RESULT} == 1 ]]; then echo "Tests failed" && exit 1; fi
-
+          gsutil cp -r ./results/allure-raw gs://er-report-test/
+          gsutil cp -r ./allure-report gs://er-report-test/
+        #  if [[ ${TEST_RESULT} == 1 ]]; then echo "Tests failed" && exit 1; fi
 
 workflows:
   version: 2
